name: Build

on:
  push:
    branches: ["master"]

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"

      - name: npm install
        run: npm install

  deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Run Lint
        run: npm run lint

      - name: Build Docker image
        run: docker build . --file Dockerfile --tag flodenoir/devopslab5:latest
        if: success()

      - name: Push docker image to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        run: docker push flodenoir/devopslab5
        if: success()

      - name: Pull docker image
        run: docker pull flodenoir/devopslab5:latest

      - name: Run
        run: docker run --memory=512m --cpus=1 --name devopslab5 -p 80:80 flodenoir/devopslab5

      - name: Ping
        run: curl http://localhost:80