name: Build

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: npm install
        run: npm install

      - name: Run Lint
        run: npm run lint

      - name: Build Docker image
        run: docker build . --file Dockerfile --tag flodenoir/devopslab5:latest
        if: success()

      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUBUSERNAME }}
          password: ${{ secrets.DOCKERHUBPASSWORD }}

      - name: Push to Docker Hub
        run: docker push flodenoir/devopslab5
        if: success()

      - name: Pull docker image
        run: docker pull flodenoir/devopslab5:latest

      - name: Run and ping
        run: | 
          docker run --memory=512m --cpus=1 --name devopslab5 -p 80:80 flodenoir/devopslab5
          sleep 3
          curl http://localhost:80